MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [12, 12]
  ID_LOSS_WEIGHT : 0.25
  TRIPLET_LOSS_WEIGHT : 1.0
  I2T_LOSS_WEIGHT : 1.0 #loss_I2T
  SIE_CAMERA: True
  SIE_COE : 1.0
  USE_SSL : True
  SSL_TYPE: 'SIMCLR'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 256
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY:  1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 120
    CHECKPOINT_PERIOD: 120
    LOG_PERIOD: 50
    WARMUP_EPOCHS: 5
    SSL_LOSS_WEIGHT: 0.8
    PROMPT_AUG_SCALE: 0.5
    PROMPT_AUG_METHOD: 'mask'

  STAGE2:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.000005
    WARMUP_METHOD: 'linear'
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY:  0.0001
    WEIGHT_DECAY_BIAS: 0.0001
    LARGE_FC_LR: False
    MAX_EPOCHS: 60
    CHECKPOINT_PERIOD: 60
    LOG_PERIOD: 50
    EVAL_PERIOD: 60
    BIAS_LR_FACTOR: 2
    STEPS: [30, 50]
    GAMMA: 0.1
    SSL_LOSS_WEIGHT: 0.8

TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  WEIGHT: 'your_model_dir'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'


DATASETS:
#   NAMES: ('dukemtmc')
   NAMES: ('occ_duke')
#   NAMES: ('market1501')
#   NAMES: ('msmt17')
   ROOT_DIR: ('/data1/wangbin/')
OUTPUT_DIR: '/data1/wangbin/Papers/SAVLL-ReID/Codes/pth/occ_duke'


# CUDA_VISIBLE_DEVICES=0 python train_svllreid.py --config_file configs/person/vit_svllreid.yml
